### ISSUE TITLE
couldn't make from git

### ISSUE THREAD

**Issue by dchmelik** [vbatts/sbo-tools#1]
d@0.cosmos:~/slack-utils$ make slackpkg
make: *** No rule to make target 'slackpkg'.  Stop.

**Comment by vbatts** [comment]
Following which instructions?

On February 13, 2022 1:41:20 AM EST, David Chmelik ***@***.***> wrote:
***@***.***:~/slack-utils$ make slackpkg

**Comment by dchmelik** [comment]
I guess there were no instructions--just trying to make the most recent commit.  I think the comment was on the wrong project.

**Comment by vbatts** [comment]
right, so, howcome `make slackpkg` is an expected target?
(I see you're opening other issues like this)

**Comment by vbatts** [comment]
oh, I see from the stale README on slack-utils. Let's fix it there
